version: '3'

services:
  web-app-laravel-docker-desafio-tecnico:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html/laravel-docker-desafio-tecnico-problem/
    networks:
      - network-app-laravel-docker-desafio-tecnico

  mysql-laravel-docker-desafio-tecnico:
    image: migs/mysql-5.7:latest
    ports:
      - "3306:3306"
    volumes:
      - ./docker/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: desafiotecnicofacilitaapp
      MYSQL_USER: root
      MYSQL_PASSWORD: admin123

    networks:
      - network-app-laravel-docker-desafio-tecnico

  phpmyadmin-app-laravel-docker-desafio-tecnico:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql-laravel-docker-desafio-tecnico
    ports:
      - 8001:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - network-app-laravel-docker-desafio-tecnico

networks:
  network-app-laravel-docker-desafio-tecnico:
    driver: bridge

