version: '3'

services:
  laravel-app-desafio-tecnico:
    build: .
    ports:
      - "8088:80"
    volumes:
      - ./:/var/www/html/laravel-docker-desafio-tecnico/
    networks:
      - app-network-desafio-tecnico

  mysql-app-desafio-tecnico:
    image: migs/mysql-5.7:latest
    ports:
      - "3006:3306"
    volumes:
      - ./docker/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: desafiotecnico
      MYSQL_ROOT_PASSWORD: 
    networks:
      - app-network-desafio-tecnico

  phpmyadmin-app-desafio-tecnico:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql-app-desafio-tecnico
    ports:
      - 8090:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - app-network-desafio-tecnico

networks:
  app-network-desafio-tecnico:
    driver: bridge

